# syntax=docker/dockerfile:1

FROM mambaorg/micromamba:0.22.0
COPY --chown=$MAMBA_USER:$MAMBA_USER env.yaml /tmp/env.yaml
RUN micromamba install -y -f /tmp/env.yaml && \
    micromamba clean --all --yes

USER root

RUN groupadd docker \
	&& usermod -aG docker $MAMBA_USER

USER $MAMBA_USER